[deploy]
startCommand = "python manage.py migrate && python manage.py seed_data && python manage.py collectstatic --noinput && python manage.py createsuperuser --no-input || true && gunicorn treefel.wsgi --bind 0.0.0.0:$PORT"
